[{"name": "test.test_explained_variance.ExplainedVariance.test_pca", "status": "errored", "message": "[Errno 2] No such file or directory: './data.tsv'", "passed": false, "points": ["p06-08.1"], "backtrace": ["  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/test/test_explained_variance.py\", line 34, in test_pca\n    v, ev = explained_variance()\n            ^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/src/explained_variance.py\", line 7, in explained_variance\n    df = pd.read_csv('./data.tsv', sep='\\t')\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 912, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 577, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1407, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1661, in _make_engine\n    self.handles = get_handle(\n                   ^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/common.py\", line 859, in get_handle\n    handle = open(\n             ^^^^^\n"]}, {"name": "test.test_explained_variance.ExplainedVariance.test_plot", "status": "errored", "message": "[Errno 2] No such file or directory: './data.tsv'", "passed": false, "points": ["p06-08.2"], "backtrace": ["  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/test/test_explained_variance.py\", line 73, in test_plot\n    main()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/src/explained_variance.py\", line 16, in main\n    v, ev = explained_variance()\n            ^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/src/explained_variance.py\", line 7, in explained_variance\n    df = pd.read_csv('./data.tsv', sep='\\t')\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 912, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 577, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1407, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1661, in _make_engine\n    self.handles = get_handle(\n                   ^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/common.py\", line 859, in get_handle\n    handle = open(\n             ^^^^^\n"]}, {"name": "test.test_explained_variance.ExplainedVariance.test_print", "status": "errored", "message": "[Errno 2] No such file or directory: './data.tsv'", "passed": false, "points": ["p06-08.1"], "backtrace": ["  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/test/test_explained_variance.py\", line 48, in test_print\n    main()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/src/explained_variance.py\", line 16, in main\n    v, ev = explained_variance()\n            ^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/src/explained_variance.py\", line 7, in explained_variance\n    df = pd.read_csv('./data.tsv', sep='\\t')\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 912, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 577, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1407, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1661, in _make_engine\n    self.handles = get_handle(\n                   ^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/common.py\", line 859, in get_handle\n    handle = open(\n             ^^^^^\n"]}, {"name": "test.test_explained_variance.ExplainedVariance.test_values", "status": "errored", "message": "[Errno 2] No such file or directory: './data.tsv'", "passed": false, "points": ["p06-08.1"], "backtrace": ["  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/lib/python3.11/unittest/case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/test/test_explained_variance.py\", line 23, in test_values\n    v, ev = explained_variance()\n            ^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e08_explained_variance/src/explained_variance.py\", line 7, in explained_variance\n    df = pd.read_csv('./data.tsv', sep='\\t')\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 912, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 577, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1407, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py\", line 1661, in _make_engine\n    self.handles = get_handle(\n                   ^^^^^^^^^^^\n", "  File \"/home/phyu/anaconda3/lib/python3.11/site-packages/pandas/io/common.py\", line 859, in get_handle\n    handle = open(\n             ^^^^^\n"]}]